services:

  evilspins:
    build: .
    container_name: evilspins
    restart: unless-stopped
    ports:
      - $PORT:3000
    volumes:
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: dockerweb
    external: true
